config/routes.rb
Wastenot::Application.routes.draw do
  root :to => "things#index"
  
  resources :things do
    post :gone
  end

  match 'location' => 'locations#find'
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  attr_accessible :description, :expires_at, :latitude, :longitude, :title, :image, :address, :reported_gone_at

  default_scope where("reported_gone_at IS NULL")

  mount_uploader :image, ImageUploader

  geocoded_by :address do |obj, results|
    if geo = results.first
      obj.latitude = geo.latitude
      obj.longitude = geo.longitude
      obj.street_address = geo.street_address
      obj.country = geo.country
      obj.state  = geo.state
      obj.postal_code = geo.postal_code
      obj.city = geo.city
    end
  end

  validates_presence_of :title, :address

  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def find
    results = Geocoder.search([params[:latitude],params[:longitude]])
    if geo = results.first
      @response = { "address" => geo.address }.to_json
    else
      @response = { "error" => "Could not determine your location" }.to_json
    end

    render :json => @response 
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things
  # GET /things.json
  def index
    lat = params[:latitude]
    long = params[:longitude]
    location = params[:location]
    search   = params[:what]

    if request.xhr?
      rel = Thing.where("title LIKE ? AND created_at >= ?", "%#{search}%", 7.days.ago).order("created_at DESC").limit(50)

      if lat && long
        results = Geocoder.search([lat,long])
        if geo = results.first
          @location = "#{geo.city}, #{geo.state}"
        end
        @things = rel.near([lat,long])
      elsif location.present?
        @location = location
        @things = rel.near(location)
      else
        @things = rel 
      end

      return render "_things", :layout => false
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # POST /things/1/gone
  def gone
    @thing = Thing.find(params[:thing_id])

    @thing.reported_gone_at = Time.now

    if @thing.save
      redirect_to things_url
    else
      render action: "show"
    end
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to things_url, notice: 'Your stuff is now listed!' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    link_to link_text, link_path, :class => class_name
  end
end

app/helpers/things_helper.rb
module ThingsHelper
  def pick_up_time(thing)
    thing.expires_at.nil? ? "Whenever" : distance_of_time_in_words(thing.expires_at, Time.now)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>waste not. landfill ain't gonna take your shit no more.</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1>waste not.</h1>
  <nav>
    <%= nav_link "need stuff", things_path %>
    <%= nav_link "found stuff", new_thing_path %>
  </nav>
</header>
<section id="notice"><p><%= notice %></p></section>

<%= yield %>

</body>
</html>

app/views/things/_form.html.erb
<%= form_for(@thing, :html => { multipart: true }) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label :title, 'What have you found?' %>
    <%= f.text_field :title %>
  </fieldset>
  <fieldset id="location_field">
    <%= f.label :address, "Where is it?" %>
    <%= f.text_field :address %>
  </fieldset>
  <fieldset>
    <label for="thing_image">Add a picture?
      <button id="pic_select" class="btn">take photo</button>
      <span id="image_label">(optional)</span></label>
    <%= f.file_field :image %>
    <script>
    document.querySelector('#pic_select').addEventListener('click', function(e) {
      e.preventDefault();
      document.querySelector('#thing_image').click();
    }, false);

    jQuery('#thing_image').change(function(e) {
      jQuery('#image_label').html('<strong>' + $(this).val().split('/').pop().split('\\').pop() + '</strong>');
    });
    </script>
  </fieldset>

  <fieldset>
    <label for="description">More details? <span>(optional)</span></label>
    <%= f.text_area :description %>
  </fieldset>
  <%= f.submit 'Post this', :class => 'btn' %>
<% end %>

<script>
function success(position) {
  $.post(
    '/location',
    { latitude: position.coords.latitude, longitude: position.coords.longitude },
    function(data,textStatus,jqXHR) {
      if (!$("#location_field input").val()) {
        $("#location_field input").val(data.address);
      }
    }
  );
}

function error(msg) {
}

$("document").ready(function() {
  if(navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(success, error);
  }

 var input = $("#location_field input")[0]; 

 var options = {
   types: ['geocode']
 };

 autocomplete = new google.maps.places.Autocomplete(input,options);
});
</script>

app/views/things/_things.html.erb
<p class="location" style="display: none"><%= @location %></p>
<p class="search" style="display: none"><%= params[:what] %></p>
<% if @things.present? %>
  <ol class="stuff-list">
    <% @things.each do |thing| %>
      <li>
      <a href="<%= thing_path thing %>" title="<%= thing.description %>">
        <%= image_tag thing.image_url(:thumb).to_s %>
        <strong><%= thing.title %></strong>
        <span><%= "#{thing.street_address}, #{thing.city}" %></span>
        <%= "#{time_ago_in_words(thing.created_at)} ago" %>
      </a>
      </li>
    <% end %>
  </ol>
<% else %>
  <p>Nothing found nearby! Check back later.</p>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<script>
function success(position) {
  $("#results").load(latLongUrl(position),function(response,status,xhr) {
    $("#location").val($(response).filter("p.location").text());
    $("#what").val($(response).filter("p.search").text());
  });
}

function error(msg) {

}

function getPosition() {
  if(navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(success,error);
  }
}

function latLongUrl(position) {
  return "things?latitude=" + position.coords.latitude + "&longitude=" + position.coords.longitude;
}

function searchUrl(what,place) {
  return "things?what=" + encodeURIComponent(what) + "&location=" + encodeURIComponent(place);
}

function getResults() {
  $("#results").html("<p>Searching ...</p>");
  what = $("#what").val();
  place = $("#location").val();

  if (what || place) {
    $("#results").load(searchUrl(what,place),function(response,status,xhr) {
      $("#location").val($(response).filter("p.location").text());
      $("#what").val($(response).filter("p.search").text());
    });
  } else {
    getPosition();
  }
}

$('document').ready(function() {
  getResults();

  $("input.btn").click(function(e) {
    e.preventDefault();
    getResults(); 
  });
});
</script>
<%= form_tag things_path, :method => :get, :class => 'search' do %>
  <%= label_tag :what, "find" %>
  <%= text_field_tag :what, params[:what], :placeholder => 'Any stuff' %>
  <%= label_tag :location, "near" %>
  <%= text_field_tag :location, (params[:location] || @location) %>
  <input type="submit" value="Search" class="btn primary">
<% end %>
<div id="results">
</div>

app/views/things/new.html.erb
<%= render 'form' %>

app/views/things/show.html.erb
<article class="thing">
  <h1><%= @thing.title %></h1>

  <%= link_to @thing.image_url do %>
    <%= image_tag @thing.image_url(:small).to_s unless @thing.image_url.blank? %>
  <% end %>
  <h2 class="city"><%= @thing.city %></h2>
  <a class="address" href="http://maps.google.com?q=<%= "#{@thing.address}" %>">
    <span><%= @thing.street_address %></span>
  </a>  

  <div class="when">
    Listed <%= "#{time_ago_in_words(@thing.created_at)} ago" %>
  </div>

  <% unless @thing.description.empty? %>
    <h3>Details</h3>
    <div class="description">
      <%= @thing.description %>
    </div>
  <% end %>

  <%= button_to "Gone :(", thing_gone_path(@thing), :class => "btn cancel", :confirm => "Is this thing really gone?" %>
</article>